name: Python CI
on:
  push:
    branches:
      - main
      - 'feature/*'
      
  pull_request:
    branches:
      - main
      - 'feature/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build Docker compose
        run: docker compose up -d --build
        
      - name: Pruebas unitarias con pytest
        run: docker compose run pytest
        
      - name: Pruebas BDD con behave
        run: docker compose run behave

      - name: Security audit
        run: pip-audit