name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check docker and docker compose versions
        run: |
          docker --version
          docker compose version

      - name: Build and run docker compose
        run: |
          docker compose up --build -d

      - name: Run tests
        run: |
          docker exec app python -m unittest discover

      - name: Stop and clean docker compose
        run: |
          docker compose down